package io.github.hectorvent.floci.config;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.quarkus.runtime.annotations.RegisterForReflection;

import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * Metadata for self-signed TLS certificates generated by Floci.
 * 
 * <p>
 * This metadata is persisted alongside certificate files to track which hostnames
 * were used during generation. It enables detection of configuration changes on
 * restart, allowing the system to regenerate certificates when hostname configuration
 * changes.
 * 
 * <p>
 * The metadata file is stored as JSON at {@code {persistent-path}/tls/floci-selfsigned.metadata.json}.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@RegisterForReflection
public class CertificateMetadata {

    /**
     * List of hostnames that were included in the certificate's Subject Alternative Names (SANs).
     * This includes both default hostnames (localhost, 127.0.0.1, etc.) and custom hostnames
     * from FLOCI_HOSTNAME and FLOCI_BASE_URL configuration.
     */
    private List<String> hostnames;

    /**
     * ISO-8601 timestamp when the certificate was generated.
     * Used for debugging and auditing purposes.
     */
    private String generatedAt;

    /**
     * Floci version that generated the certificate.
     * Used for debugging and potential future migration scenarios.
     */
    private String flociVersion;

    /**
     * Default constructor for Jackson deserialization.
     */
    public CertificateMetadata() {
    }

    /**
     * Creates certificate metadata with the specified hostnames.
     * 
     * @param hostnames List of hostnames included in the certificate SANs
     * @param generatedAt ISO-8601 timestamp when the certificate was generated
     * @param flociVersion Floci version that generated the certificate
     */
    public CertificateMetadata(List<String> hostnames, String generatedAt, String flociVersion) {
        this.hostnames = hostnames;
        this.generatedAt = generatedAt;
        this.flociVersion = flociVersion;
    }

    /**
     * Creates certificate metadata with the specified hostnames and current timestamp.
     * 
     * @param hostnames List of hostnames included in the certificate SANs
     * @param flociVersion Floci version that generated the certificate
     * @return New CertificateMetadata instance with current timestamp
     */
    public static CertificateMetadata create(List<String> hostnames, String flociVersion) {
        return new CertificateMetadata(hostnames, Instant.now().toString(), flociVersion);
    }

    public List<String> getHostnames() {
        return hostnames;
    }

    public void setHostnames(List<String> hostnames) {
        this.hostnames = hostnames;
    }

    public String getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(String generatedAt) {
        this.generatedAt = generatedAt;
    }

    public String getFlociVersion() {
        return flociVersion;
    }

    public void setFlociVersion(String flociVersion) {
        this.flociVersion = flociVersion;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CertificateMetadata that = (CertificateMetadata) o;
        return Objects.equals(hostnames, that.hostnames) &&
               Objects.equals(generatedAt, that.generatedAt) &&
               Objects.equals(flociVersion, that.flociVersion);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hostnames, generatedAt, flociVersion);
    }

    @Override
    public String toString() {
        return "CertificateMetadata{" +
               "hostnames=" + hostnames +
               ", generatedAt='" + generatedAt + '\'' +
               ", flociVersion='" + flociVersion + '\'' +
               '}';
    }
}
